apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: rag-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`minio.jeans-host.net`)
      kind: Rule
      services:
        - name: minio-console
          port: 9001
