apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rag-system
resources:
  - helmrepository.yaml
  - secret.yaml
  - user-rich-secret.yaml
  - user-alist-secret.yaml
  - helmrelease.yaml
  - ingressroute.yaml
