apiVersion: v1
kind: Secret
metadata:
    name: paperless-config
    namespace: rag-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:hSJD1y6sMx3wyFA4nU1zNuvERb80mPA=,iv:0dMmaTh8gtzq5nd/srYenYLJ/ChCZLMIkitiEmMUwbc=,tag:u2HYgRDnvr0zGAwGJXIA3w==,type:comment]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:0OJPhV179oORwCjk1rNM3Hye/Lm+Nxf5TtE/WAkadMJvW5MAuNW+1wJYP0M=,iv:KeJW7t35pc5izfdxQXkepFJB5Z/z/IQlNmVG66BQygI=,tag:N9Hvt6BOIeU+zo+0SqogXQ==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:eco6RQ==,iv:9OD1HWYive095msD6h1eJjLnI34vH7DvNJj++bDifYE=,tag:RDbNv5KbGBZxNOeKMukLUg==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:rKQH8VhxAfe1,iv:JiwdHveRDzFFzmC6Zhk1vl9HK4IptH87lMW5mryQd+k=,tag:pP2W61f+V+1E98BJA2DMWg==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:/Q3YE2Wn1zu6,iv:REUnADg4GkQnr3JZeV9xOb7brx88ndcm3726i8mXSFw=,tag:fP1nhqHlZzfMSNnexvzjBg==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:j+/SQukTGyujIl68uaMtuGsEI8b10Mx8hxNhMd3zuA/CuSqh9bnwQt3Jw9Y=,iv:LfuyLI6O046hyDZKsHNDjD6kDUYe5ilSBCMJWy51BZQ=,tag:/zFDq3bdw6mMcRmtZ2lOzA==,type:str]
    #ENC[AES256_GCM,data:jvgvYHO3bYjvxBOIbjDLgnmCEI0=,iv:apKOhuVlo6adCPdpUshjTvJiiZF0qRSFnjjorLzHIwc=,tag:uVzinJKl4cXelLI135mJ8g==,type:comment]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:St/NRf4lZ+wKNT0u6NJ0u94Beo5yiYP0fX1BAk8CTXYo44KByNI20TWYeDEmhOU=,iv:7sacMOt+kEFBVYH++Im98vHMqRAP5Ul1gCC0EW9J4+k=,tag:obkYgYheK3DrYQf2u9qI/A==,type:str]
    #ENC[AES256_GCM,data:Us2gaEoj/a8UtB8/f3udJg2MklcH2mg=,iv:EgZOdSGfYa621ETMCtPCU2Fj28KTlJWridqqTVZKbqk=,tag:H0NBvAHK00lUmz+i0ZZdMg==,type:comment]
    PAPERLESS_STORAGE_TYPE: ENC[AES256_GCM,data:+9k=,iv:NKaXo1MSRzaa9nklNFuIAxHjvVsulNbj5JTpB+aVFmI=,tag:WeAZJN/gqyB2d1eq3ahS3w==,type:str]
    PAPERLESS_S3_ENDPOINT: ENC[AES256_GCM,data:6GzsR+GEl1cPlf683IzYkk1zaDj7IrT8Imt02cgOmYnAqrRzmNs7UV5Eh+t/AQ==,iv:+rQ5PLQeHq4WCokF7HJ1ZdmRLUU1bvnNO2klSyHrHKc=,tag:048JgQ9snF7oDSE8bMJqVw==,type:str]
    PAPERLESS_S3_BUCKET_NAME: ENC[AES256_GCM,data:QbH1xpuhRUkSsdClAA==,iv:5oGXGvdgyt6RTEpbApmYcTo4+OqWDWvAUT7DgPU6q0M=,tag:LtK2Ja9yxIIiSLi04+hGZw==,type:str]
    PAPERLESS_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:bNZmbBm2KUfVAHtCiYoRCqs=,iv:zc/hM2dm2F6h5HAHluoTUVBVT2zmp3RuLjwyw+Ef1Us=,tag:Vxp1sNsW9u+FKeI1lMDsNQ==,type:str]
    PAPERLESS_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9jDgXOXSMeOd1dCZCAwrf9d2ZG0cFyTzvfbmB9i3CYiKn77pozgdLad5iyg=,iv:I2GW904qpkZ8Yf2V5rLZOiZXQzeeKVDS5VrjmWmmHEc=,tag:LFw2wtoon13Oi6TmvN2k1g==,type:str]
    PAPERLESS_S3_REGION: ENC[AES256_GCM,data:W25H9XolcxWL,iv:wLjt4246BC40XAFTJZ689IctIAX66qF3LU292txeZ3g=,tag:cJbr1Ep86ayrTvJYvQEa4A==,type:str]
    PAPERLESS_S3_USE_SSL: ENC[AES256_GCM,data:7XKNKMs=,iv:LHcJ0F/Swtw/hUZH2PRtFyuDfVWIyDWte66F+J3XeOA=,tag:OE/favx9zilYf3EKgSIGMQ==,type:str]
    PAPERLESS_S3_SIGNATURE_VERSION: ENC[AES256_GCM,data:WfFz8w==,iv:8b+6n9EHzHW6500zjR2kCP1hcQ4VDGqxMI0CPhYWL9w=,tag:4UyBwev1LJGhdmLh8O7mkA==,type:str]
    #ENC[AES256_GCM,data:+buDQtQnKn8SawG4aFkVPI/Vb8Fl58pL,iv:moHQIVn/yUvN/ZB2XloRRI6ba+puMzlnTibpk5beNLQ=,tag:tI628I2xHBHEeLht+nRvJw==,type:comment]
    PAPERLESS_URL: ENC[AES256_GCM,data:gRS2pTbvzC+RBFGn4xq0L9DoGVIzogx+f5NvF2Oswp8=,iv:Q78ZJMgBjwRCwQapw0jwk4XAWQ7vTIsYXhsuZBmgTGI=,tag:iA/GUR+oUZQdAKzbBPbCIw==,type:str]
    PAPERLESS_TIME_ZONE: ENC[AES256_GCM,data:JyLzklPvGtUb0dCMw577w8ykoQ==,iv:2gk1RQIFjUV8z/YCkfMkWXNvpDwlGTMoW50KNcuFnZY=,tag:IeBQkSykQdGAIAmrNH224Q==,type:str]
    PAPERLESS_OCR_LANGUAGE: ENC[AES256_GCM,data:Y65S,iv:XcLFskNHxneGBceQaKVmqmrczGap61DdIfQDPUsYjLs=,tag:2J6+bFNrL/oQFATusLlgCA==,type:str]
    #ENC[AES256_GCM,data:0lxXLTxP2lpVqQIRsxIy9w==,iv:r14ZP46z8hM+vwhHrKKxcswaWPKelwPkaoj3XdWDgDY=,tag:kQ0yjNpFXWPGEIREGGuPBg==,type:comment]
    PAPERLESS_FILENAME_FORMAT: ENC[AES256_GCM,data:vlkjYhBG0v6MhGeMV0ufOb1InjbW/znzh1Le/ELcYQiVA9lpSjA=,iv:XGiTy2vn6k49fa1ZX5OatA8zsDfOX5qF6Nq6kTVk/Rs=,tag:t/OohuHTiR+5UEe93bhuNA==,type:str]
    PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: ENC[AES256_GCM,data:y6oVgw==,iv:dorFVdgo475SJqUsfwrDVtV5yCZDQkCmU3CMbnexCrI=,tag:gz4TD94JhrccRGtdPcK/mQ==,type:str]
sops:
    age:
        - recipient: age1p26qk2kerzdf0dj705ergv7smregn6tfy02yxwhmmdv4ldh2vqaqxvpz3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxc0hjV2dadmtPSEM2cGxz
            V2p4eHF0VmFqcmZ4SmVjalhab0Ivbmc5NGd3Ci8wSEtFczluM243VmROcVRYeUlj
            aC9vNU1CaXlHR0tqdTVMNklmbzhCVk0KLS0tIEFZdm5hbnRrU1o0TVhFZUVrd3Bl
            UlFXZ3J3dmcxdmVtaWtNYWRyeGpqN1UKAfi52q+uHtVcLf1M4yuLrkkl3MbdO9nf
            cmvZ+ncdOwOyDUYgvPsLyyKza4b5eGdN/7i4KdYaQYFOSGLruxAgLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T12:21:29Z"
    mac: ENC[AES256_GCM,data:TiBuY+tQhcCGvfNHEMlB0qPQSXNggI6DlkYuDKWC6a07JK2PqvzSxGrj/AsrEddVEMulpYqmovgv7ZxwBI3MFyifnpjBNErWJx/HklvST/syCOonjhDfAAKy+VN7aXtyOB7VUO3d2cQY924pg4bvPs7+dXXob7h5K4ItlCyaF2M=,iv:3hR7wb92JXqVgMrrfmNKDTt0P2AEkCle4JxZgKQGaVM=,tag:ZujKe9I8MwiH364aH/MYSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
