apiVersion: v1
kind: Secret
metadata:
    name: paperless-config
    namespace: rag-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eopLWjrIM1xVCkExF/YUokBcOdK11uE=,iv:viovodkXVwO9rm2R84WLl9rDDwyubv6Uc8kVH6UzDio=,tag:uZyaLWfL4KbnhwYn3N3PZA==,type:comment]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:Yb5VHdTOGD6CD+/Heo9Eio3SEAUaDba89QExe6yGVktfLRHOEAwkx5Dw3yg=,iv:sUw67hVCJ4LvdFd51COHq3dgSK+W34kKMNtVpme1YXs=,tag:MqXFp/4p+1aE2DaZpMLASA==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:XEGq0w==,iv:Kge/kG4FBbMuGQQFiB9u5xAVtjWedrCxjWAyrfUPadM=,tag:Npd4gMl+lkTFI5s616FGCw==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:k1CVbd7c/uSu,iv:/kIGo0XeMivBH1VRmxUM245ZL9EdAld/7x0ZuhFtI+s=,tag:kB+aV07QZ/4kNfPBt+rmKQ==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:Xe0c2zXPu4vS,iv:28c8vWuzz8rg6N84iZn3p3/Xev+g2GjDNnCm5EYxMFo=,tag:9YxBxUdhxHgzTT0MXTJp9g==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:+dgGA8J08hG4OSsUBKAp4pN58XZxZTMryKndADjpGeGUXmXrOzwaYUv7xNE=,iv:9SqyONffU/XOsGYLEg7vEwwG1H43PBooqL2CFsRIr5Q=,tag:V6y+3SK3L6fxqz3wh+saug==,type:str]
    #ENC[AES256_GCM,data:PfNvYs3DELaRYK2CwWHr5PFCKWQ=,iv:ISNlSt8hUhbPfbvEchnFyWUBBsaQYCYQ9Z6nDZ69CrI=,tag:2js5IypIDnVRWJySuiXnzg==,type:comment]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:d17tXICeAXK0zzPRFuEFzbGHvPQeDqoaWne06tUfK58wFug3oH0P3o6oTaE/UtE=,iv:OaPM2RSElFEq9PO5ZdvhSCbXyIdjiG/IYoDZsTKLqA4=,tag:MgshleEIraldXmDL/r0ddQ==,type:str]
    #ENC[AES256_GCM,data:+kx9AkdKtBUcpdt8eM+n2D0s0SiE57w=,iv:rM0Bp+rarSGk2Cv6Q1VU/7cXZ4ZQC6h2ZlqvOPazujw=,tag:t9UT2hgTo6yExrGNLXB2qA==,type:comment]
    PAPERLESS_STORAGE_TYPE: ENC[AES256_GCM,data:f74=,iv:zFD71YyWU7n5fYN6PzFBlapj4htupCxTiK9E0fpGRRk=,tag:DPjKRFDWkDU0CVPFeVzp6w==,type:str]
    PAPERLESS_S3_ENDPOINT: ENC[AES256_GCM,data:aSssyUOnjL3tIrxA1fuWm5Xr9XUo1VRL8HESfqBpt/DVi7ZGWYgsGpTbE4lTfA==,iv:2aBVUkvYddVeq3Ls50WanbBviGDZVEHQdoAHuAuhT0Q=,tag:BFULX1Scwh4iQYNMnToZYA==,type:str]
    PAPERLESS_S3_BUCKET_NAME: ENC[AES256_GCM,data:sWeBVnWqrL30i4yH1Q==,iv:kay0lJXctub1XxKcULKL69TiFw9m5gFI0Q3UhKZDtas=,tag:4SBAy5xAsg7g5gT9z3jFVg==,type:str]
    PAPERLESS_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:xQQxzmPKTUwO13myA5v3/Ek=,iv:rfj1eO4szeytHEKkQZPGwbDU5jjNEufnQvXFOMAiRFU=,tag:h+Ao7uOZA13+JugdN1V7GA==,type:str]
    PAPERLESS_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PQZ8OtMoCW1OQKS93a57RBR/LW14H6xPN8sP2bx0edQkv9K7Fi1qnN1L/TU=,iv:LrqqoRsBlzAKGXqDqgWvuBfY1NcRECY5pzf4ub7eA24=,tag:NXMyB/0/O4PnPq11mt668g==,type:str]
    PAPERLESS_S3_REGION: ENC[AES256_GCM,data:CNMVESoDgPkE,iv:p+Ki0TIq0XsrsBTpbskFkppDOeUI4Go5L6+P6TCwtdU=,tag:CxGisfhLCWSubdwbcA5ptA==,type:str]
    PAPERLESS_S3_USE_SSL: ENC[AES256_GCM,data:ssMsQXM=,iv:pCEs7Ebxns6iwS5bOIvpGAV0lyHKoWM9kCd+DL5FIBE=,tag:YRB2GxPRlZE3Ry1gdronGA==,type:str]
    PAPERLESS_S3_SIGNATURE_VERSION: ENC[AES256_GCM,data:YqSt4Q==,iv:S611cEzOZ4AZOgArhmQvXhwsq8oGqH9HE9SzN1KZt3Q=,tag:1eTKfXwAhBhDbtnMzQJOow==,type:str]
    #ENC[AES256_GCM,data:Wk4kuW/TW8NSeSF7mx23HZ7UL3ONhoNU,iv:TrQF1TAIWXX/3pnMOkEoSNztIcJ7ikqobwbsJxzmVF4=,tag:r2n9AGOx5o7xJNLK9h9zKQ==,type:comment]
    PAPERLESS_URL: ENC[AES256_GCM,data:wF34t+ityKS86GxbMx9vjDU8CLUGsU5VXH5x7dgsdDY=,iv:yCstjtZ8TC/EsOjvO2nI8JLD46L0C1xCg2S8VLKkRnw=,tag:fsIza1gzZkn1i2f0d4B20g==,type:str]
    PAPERLESS_TIME_ZONE: ENC[AES256_GCM,data:3T5mt4ckm+z+vXrPp3QMNqyHOA==,iv:/OUCWSENm/sBAFwGT6KJUdZP1nA0cKoNGuAvXKV/SlM=,tag:CGC8gN1fP9qtb0wR1CmU5w==,type:str]
    PAPERLESS_OCR_LANGUAGE: ENC[AES256_GCM,data:Zbtm,iv:Q7f77Gmy3oJV9YpSS6NmTnZ5NAsSXBbPC9jEn3ykumg=,tag:0fOt9pWP4D43aR6+6vbSZw==,type:str]
    #ENC[AES256_GCM,data:Y5GMz7BuI77I322e0VS/Xw==,iv:2o97p4RZkb7CRNmfnRlWeUbN26n+C20m55RhWqf+iZ4=,tag:Qo+QCVvJPxxwsk+1laCg7w==,type:comment]
    PAPERLESS_FILENAME_FORMAT: ENC[AES256_GCM,data:0ifZj9pG3SnAPKKQ8YRwF8meUwbrk7xJ3Otb8A7wvuxuDXReXSfwGIHbGhWoBuXXXCw=,iv:ZD5yJgR0tKX48BAQwbRnvrs+fzt9rbkFGjHlFX7iMVI=,tag:XatAM7CGgQGVJzJfzFP0iw==,type:str]
    PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: ENC[AES256_GCM,data:N/8fYA==,iv:FGlhRqnIyACX7VuuNhsv1lefYmSKo2kv366wwjrTSxk=,tag:sYyA9+j//na8GOiM3heTjg==,type:str]
sops:
    age:
        - recipient: age1p26qk2kerzdf0dj705ergv7smregn6tfy02yxwhmmdv4ldh2vqaqxvpz3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyLzdleXBwSSswcnByUnNa
            SysweGxvVk1xNzhoalN5Q3NEcEtReXVGV1JnCmprRkNDdkRLS0NBZWRMeUNpZXpk
            MmhML2w5N1hPQzhXQk4zQk1haW1vQ2MKLS0tIGw3NzhFN0ZKRFd5RnRNSGRMQTlH
            dldvZy9jS1FMZ1pZK3V2cTJRa0thQjgKvW3HVjdzpmFuRNRg+9WS9sOFfuknAS7i
            +38yxNCnNIHfus7M/Sb6Lb8UoUckzSi7Hzt7RqEbdtaTVESzN0ytaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T12:26:43Z"
    mac: ENC[AES256_GCM,data:ZF2mMUs+LB2wumEqv4UFuPdIfhiah7YBJWMM6kMbEklQuTQ1e8tooBDfqiX19adzLFmlSkmEFSyUXTuCINlhJxRfzIWsBaFfc2L8J26M0X3T0CO4AEK+YKvJokVzRQc5Zi821qmi0K4Xcmdaq3QgD5VBKR7iY2xNzOdoJsQPi5U=,iv:GAnNdW5JA66R0s9Wv5dAO5UB4H5DJnP4PIh+gvXOdTw=,tag:iDMZYgOAPDSDUyWlTJgbCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
