apiVersion: v1
kind: Secret
metadata:
    name: paperless-config
    namespace: rag-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:X6VgjvYWQdHp4706Lyy1CGfkgC/lh10=,iv:Uv1urE3MHsnFy/VuoYMAfeJU7w7abQqyPPqP+0Sq5+k=,tag:NLDgnM5IS9yOhF6OA3j9sg==,type:comment]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:k/kqVPPG2U6u3tChsavWu3DkB1wO9gexj9RQ4CrFmV5KYM7qTlNWT79vWHA=,iv:puXdbyfyaP8zPTE/pFY9Q0YqaJOCVx1wj/fnsdSDaAc=,tag:kG8DNNjFAFebdRubQP9Viw==,type:str]
    PAPERLESS_DBPORT: ENC[AES256_GCM,data:eddlsA==,iv:vt2GLAGWpDkoA7shJHMDwIDvwG3d9tXoeSm0Dp4MePY=,tag:vrXPqu6oy98a3CNIh0KVzg==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:rEiXA1Z3/zBx,iv:Mxl0YMnAauTuermIX2OzEWGvGE8cZyGFRKdFlKZYoK0=,tag:djH4w9IAGcbnoAsO9Cw8Aw==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:dgGnXFHUKgmk,iv:CGwJxDdxgKmsdNICL9Msg81LNRILWc5C25mW6/uE/dE=,tag:IPEjwjqJSdUtviNtuiwXuA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:obdqY/hjdYUUDb4ifzojLjxWwpgVyk9x0IoZ0LdccEipcUIL1dW0XNLrBeM=,iv:IkL4nDrNOxyW5SIwE3+ouhu3aell696lE1hThXTSsAo=,tag:+5hdL3BkgVMP0D/693PaNw==,type:str]
    #ENC[AES256_GCM,data:DfIeYfkZIJRFwL+VSQheCfUNmTk=,iv:MoZnud1Yb0Ow16+RqfWE4qRmMhfc3/RCBxGMCK7p2Jg=,tag:Oq/s5EABgXAhbpGCbyH4qw==,type:comment]
    PAPERLESS_REDIS: ENC[AES256_GCM,data:Pc1D20cjcIx3K5hBt/Z+lk93WPXK1PL9nLF/0+LO5kfQNVu0q4CwvXoc990RmjA=,iv:RLS0RL57ietxhO/+X2NJysOMGJq16avOZrfptROK9Ww=,tag:CrE/mzaEJ4t+3QfU0IeUxw==,type:str]
    #ENC[AES256_GCM,data:wV2HE+FYDMdmkkIKBAYIYm9asOv7UmA=,iv:5bL5/j77AgioIxwncw8VMf8F6UXAhNOUIkCUZ/md+D4=,tag:3Q0f3Yjiic6iLLRRuLkKhg==,type:comment]
    PAPERLESS_STORAGE_TYPE: ENC[AES256_GCM,data:RPA=,iv:dBmAjUOjRx1cOhNFd/JSQUkX0fll5DHX+GGpA5Xbjbw=,tag:E2sX31xah+FG2zbGWHkFCQ==,type:str]
    PAPERLESS_S3_ENDPOINT: ENC[AES256_GCM,data:GmQYJbIRS7biM/RcLFsmwAW3wiKOyssj2g31HsIDSTpgIIaq2BXKgOKVWVa7GA==,iv:eXSCYzWxUh/nppwJghCA29PL8b1OK/0YTXmRfhRkIYE=,tag:OT5eQ+GOYQ7RqxmKFVm1DQ==,type:str]
    PAPERLESS_S3_BUCKET_NAME: ENC[AES256_GCM,data:HekYK3gvHfeyIzB2Ag==,iv:HfxpVttdq6GDuNiEtpeigS1zTu6wftxTWZqobFws9Kw=,tag:8XsDFWckMn+fiRQvgTDn6A==,type:str]
    PAPERLESS_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:Yr9DZkEh9eGCb4DlaYepjok=,iv:BnyvmtCfCdpMNpe77NF+SPzEFrC+xg9CsVnS+l2QYSE=,tag:JrHcMbir7JmnvlpkMRQLpA==,type:str]
    PAPERLESS_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Nh9J77Bewz2g3mlra35WyaUc5SbCq6VnGfX1JfYYuLu0CiFwhNVPDXNMcIU=,iv:1TiFXia4xh22VIDghFFWK/YBomgzLaf+3fVhyc0vq+o=,tag:GUWZaNb4VZ2HS7JTWodZfg==,type:str]
    PAPERLESS_S3_REGION: ENC[AES256_GCM,data:wFhiOVPGnpHS,iv:2r9alcdDXJUQ2aZxqmLwtCCIZMuWTuJyZIGAtOzUqfo=,tag:OCnPM+QfO5kInal4ec/0oA==,type:str]
    PAPERLESS_S3_USE_SSL: ENC[AES256_GCM,data:fWd7EFs=,iv:80enjppxfyRjo2Vx3mdXKmCQVpNcWSzeDDwPgkI6Ass=,tag:iWA4FfSn98MYXZNXwRvvSA==,type:str]
    PAPERLESS_S3_SIGNATURE_VERSION: ENC[AES256_GCM,data:nVlwDg==,iv:gpoW5GCPjtjgW9iyLFKS7aYuPAYjo2dJ/vh0oRdj/XI=,tag:A6BicfskGlLrEDFkHJJRKA==,type:str]
    #ENC[AES256_GCM,data:LPZDg2GJOqs2PZs1aksTtkUrRYkkTcFQ,iv:7wKnY3NtasDYPIHhcoYctxUeP2yNbsO3IZHZlqKwPLU=,tag:d0nWkEopuuLXlYjGDaPOsQ==,type:comment]
    PAPERLESS_URL: ENC[AES256_GCM,data:1KEY8vetygE8UTbfXU0gXutmZzfXSp3r3xqFhg==,iv:8ZPMHKELhl4fnDzoIkmr6dk6GB4+u6oeH3Ni2qjmmyQ=,tag:m5h/A8oG+56WTrFhjZfYpQ==,type:str]
    PAPERLESS_TIME_ZONE: ENC[AES256_GCM,data:YPqEd4HfpTygy841OmGZyzYuew==,iv:K6WSRg64rDPR78ucFR5arPzCcdflHcr45vZfO+tu+qU=,tag:WIqRMB6I3ref+2yrNM42Aw==,type:str]
    PAPERLESS_OCR_LANGUAGE: ENC[AES256_GCM,data:/KW6,iv:bbne5u5m998iSE5A8YUYQZlu8AJnyh4B3srtQl2LRiM=,tag:WPrrWUE8M0XjXXwEVsAQ2g==,type:str]
    #ENC[AES256_GCM,data:SR2+giPDuPOIaG2s7H1c8A==,iv:dWi/eFpoYI1ldQz4ryFM1/x/c08J4figkm4Adb8DDEM=,tag:2/WiAdgRwDK2wr4Q0yHx7g==,type:comment]
    PAPERLESS_FILENAME_FORMAT: ENC[AES256_GCM,data:7vRCCUs6w223woLUdmZAueUAG5rfWy6CGZqwu/4yvBGb2VaXjGI=,iv:So7K6hQozjWvxGh99S93ReswS43pklR4/zGa6dwAL4s=,tag:Bx/+ixEjFXe+DMtelVfAoQ==,type:str]
    PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: ENC[AES256_GCM,data:QxPXZw==,iv:J8s6v4eh+m/eJtlVlGMjJWG2Y6xR9w1xrjO8UENi+Ac=,tag:RGHxTOYx/nac4PtFc7WuqQ==,type:str]
sops:
    age:
        - recipient: age1p26qk2kerzdf0dj705ergv7smregn6tfy02yxwhmmdv4ldh2vqaqxvpz3t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlAybm1pSG53bnlxdTZR
            dzl1bE1SNVVsNzlPNFQyM1d2WlRuRU1rMFVrCnhRM0xnYUdkQjl6SDZtTzJQdDR4
            ek4yRlB6L05TdllzWlZ6QUsyY0xnK1kKLS0tIG5FVGVNbk0vKzZOOTZVdGE5SGF1
            aUZwMUNPRU1HVDUwUTVDZUlodVhuTVEKALrkbp/UPDUIFkmDzKDA1CZGSM1Jorzb
            Af2wX1hiMzs4CNEFkLli+Q3teG0geZRi8MUgkVBnRoGcYfkk+WSocw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T11:18:21Z"
    mac: ENC[AES256_GCM,data:/DXhr9QkFyXj6Pgv46b+UgtO9o/Xr3QkSlegz2pCJIDQhgJMMDLAOnYjAiAT5IC854F0L7+kr6gda9w7oNiin2rNopZOLJQJvvmh9gKbDJ90nmxboQGHyb4q7t4+6rgcHkgw9lkG+PlZVlaf7sBgXydEdcvBOGMAuMePOEX0BmQ=,iv:RilYbo0JAXhWN6KNFmjZpqiGsJEC3qw/dU9/v5FFSHU=,tag:opekJLkojgiPUmuC/b4koQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
