apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: rag-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`paperless.jeans-host.net`)
      kind: Rule
      services:
        - name: paperless-paperless-ngx
          port: 8000
