apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rag-system
resources:
  - helmrepository.yaml
  - admin-secret.yaml
  - config-secret.yaml
  - helmrelease.yaml
  - ingressroute.yaml
