apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik
  - metrics-server
  - cloudflare-tunnel
  - longhorn  
#  - ops-debug
#  - local-path-provisioner  # Replaced by Longhorn
#  - kube-prometheus-stack
