apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik
  - metrics-server
  - cloudflare-tunnel
#  - ops-debug
#  - local-path-provisioner  # Must deploy before kube-prometheus-stack (needs storage)
#  - kube-prometheus-stack
