apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudnative-pg-operator.yaml
  - postgres-rag-cluster.yaml
  - postgres-rag
  - minio
  - nats
  - redis
