apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - namespace.yaml
  - secret.yaml
  - users.yaml
  - configmap.yaml
  - deployment.yaml
  - middleware.yaml
  - ingressroute.yaml
