apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alist
  namespace: alist
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`files.jeans-host.net`)
      kind: Rule
      services:
        - name: alist
          port: 80
