apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alist
resources:
  - namespace.yaml
  - minio-credentials-secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
